name: usersecurity
services:
  chatdata_sys:
    # 使用构建的Docker镜像
    build:
      context: .
      dockerfile: Dockerfile
    image: usersecurity
    restart: always
    # 设置容器名称
    container_name: usersecurity
    # 指定端口映射，将容器的8080端口映射到宿主机的8080端口
    ports:
      - "8082:8082"
    volumes:
      - ./log:/log
      - ./config:/config
      - /data:/data
      - ./usersecurity-0.0.1-SNAPSHOT.jar:/user-security.jar
    extra_hosts:
      - "data.moe.edu.cn:10.20.121.97"

